#  <centre>Complete Analysis of Titanic Disaster data<centre>

## Table of Contents

1. [Objective](#section1)<br>
2. [Importing Packages and Collecting Data](#section2)
3. [Data Profiling & Preprocessing](#section3)
    - 3.1 [Pre Profiling](#section301)<br/>
    - 3.2 [Preprocessing](#section302)<br/>
    - 3.3 [Post Profiling](#section303)<br/>
4. [Analysis Through Data Visualization](#section4)
    - 4.1 [What is Total Count of Survivals and Victims?](#section401)<br/>
    - 4.2 [Which Gender has more Survival rate?](#section402)<br/>
    - 4.3 [What is Survival rate based on Person type(Male,female,Child)](#section403)<br/>
    - 4.4 [Did Economy Class had an impact on Survival?](#section404)<br/>
    - 4.5 [What is the Survival probaility based on Embarkment of Passengers?](#section405)<br/>
    - 4.6 [How is Fare distributed for the Passengers?](#section406)<br/>
    - 4.7 [What was Average Fare by Pclass & Embark location?](#section407)<br/>
    - 4.8 [ Segment Age in bins with size of 20.Also Correlate Age with Survival.](#section408)<br/>
    - 4.9 [ Did Solo Traveller has less chances of Survival?](#section409)<br/>
    - 4.10 [How did Total family size affected Survival Count?](#section410)<br/>
    - 4.11 [How can you correlate Pclass/Age/fare with Survival rate?](#section411)<br/>
    - 4.12 [Which features had most Impact on Survival rate? ](#section412)<br/>
5. [Conclusions](#section5)<br/> 

# 1.Objective:

The objective of this project is to conduct complete **Exploratory data analysis (EDA)** of Titanic data in order to gather insights and eventually predicting servior on basis of features like age, sex, class , cabin and etc. using machine learning models.

**Why EDA?**

- An approach to summarize, visualize, and become intimately familiar with the important characteristics of a data set.
- Defines and Refines the selection of feature variables that will be used for machine learning.
- Helps to find hidden Insights
- It provides the context needed to develop an appropriate model with minimum errors

**About Event**

The RMS Titanic was a British passenger liner that sank in the North Atlantic Ocean in the early morning hours of 15 April 1912, after it collided with an iceberg during its maiden voyage from Southampton to New York City. There were an estimated **2,224 passengers** and crew aboard the ship, and more than **1,500 died**, making it one of the deadliest commercial peacetime maritime disasters in modern history. This sensational tragedy shocked the international community and led to better safety regulations for ships.

#  Data Description

The dataset consists of information about passengers boarded the Titanic, contains passenger name, sex, passenger class, age etc.The dataset comprises of 891 rows and 12 columns. Below is a table showing names of all the columns and their description.


| Column Name   | Description                                               |
| ------------- |:-------------                                            :| 
| PassengerId   | Passenger Identity                                        | 
| Survived      | Survival (0 = No; 1 = Yes)                                |  
| Pclass        | Passenger Class (1 = 1st; 2 = 2nd; 3 = 3rd)               | 
| Name          | Name of passenger                                         |   
| Sex           | Sex of passenger                                          |
| Age           | Age of passenger                                          |
| SibSp         | Number of sibling and/or spouse travelling with passenger |
| Parch         | Number of parent and/or children travelling with passenger|
| Ticket        | Ticket number                                             |
| Fare          | Price of ticket                                           |
| Cabin         | Cabin number                                              |
|Embarkment     | Port of Embarkation (C = Cherbourg; Q = Queenstown; S = Southampton)|

# 2. importing packages and collecting data

In [301]:
import pandas as pd                  # for data manipulation
import numpy as np                   # for linear algebra
import matplotlib.pyplot as plt      # for graph plotting
import seaborn as sns
%matplotlib inline

**importing data**



In [302]:
titanic_train_data = pd.read_csv("https://raw.githubusercontent.com/vis2208/Titanic-Project/main/titanic_train_data.csv")
titanic_test_data = pd.read_csv("https://raw.githubusercontent.com/vis2208/Titanic-Project/main/titanic_test_data.csv")
titanic_train_data.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

# Examine data

In [303]:
titanic_train_data.shape # data Shape, 891 rows and 12 columns

(891, 12)

In [304]:
titanic_train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [305]:
titanic_train_data.isnull().sum()  # age column have 177 entries null, Cabin - 687, Embarked - 2

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [306]:
titanic_train_data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [307]:
titanic_train_data["Survived"].unique()

array([0, 1], dtype=int64)

In [308]:
titanic_train_data["Pclass"].unique() # Total no of Passengers class 3.

array([3, 1, 2], dtype=int64)

In [309]:
titanic_train_data["Sex"].unique()

array(['male', 'female'], dtype=object)

In [310]:
titanic_train_data["SibSp"].unique()

array([1, 0, 3, 4, 2, 5, 8], dtype=int64)

In [311]:
titanic_train_data["Parch"].unique()

array([0, 1, 2, 5, 3, 4, 6], dtype=int64)

In [312]:
titanic_train_data["Embarked"].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [313]:
titanic_train_data["Cabin"].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [314]:
len(titanic_train_data["Cabin"].unique()) # len counts nan also

148

**insights:**
1. Dataset contains total **891** passengers records  which is 40 % of total passengers **(2224)**   aboarded on ship.
2. Dataset have **12 feature columns** with a survived column which tells about passenger survived(1) or not survived(0).
3. age column have 177 entries null, Cabin - 687, Embarked - 2
4. Survived column have to categorical value(unique) i.e; 0 & 1.
5. Total no of passenger class is 3 i.e; (1,2,3) .
6. There are only two type male & female sex category of passengers.
7. Maximum Number of sibling and/or spouse travelling with passenger are 8 and minimum 0.
8. Maximum Number of parent and/or children travelling with passenger are 6 and minimum 0.
9. Number of Port of Embarkation are 3 i.e; ('S','C' & 'Q')


# 3. Data Profiling and Preprocessing

# 3.1 **Data Profiling**

By pandas profiling, an interactive **HTML report** gets generated which contains all the information about the columns of the dataset, like the counts and type of each column. 

1.Detailed information about each column, coorelation between different columns and a sample of dataset

2.It gives us visual interpretation of each column in the data

3.Spread of the data can be better understood by the distribution plot

4.Grannular level analysis of each column.

In [ ]:
pip install pandas_profiling

In [ ]:
from pandas_profiling import ProfileReport

In [ ]:
profile = ProfileReport(titanic_train_data,title = "Titanic report")
profile

In [ ]:
profile.to_file("Titanic_Report.html")

# 3.2 Data Preprocessing

1. Check for Errors and Null Values

2. Replace Null Values with appropriate values

3. Drop down features that are incomplete and are not too relevant for analysis

4. Create new features that can would help to improve prediction 

**1. Check for Errors and Null Values**

In [ ]:
null_info = titanic_train_data.isnull().sum()
null_info_percente = (titanic_train_data.isnull().sum()/len(titanic_train_data))*100
null_data = pd.concat([null_info,null_info_percente],axis=1,keys=["total","Percentage"])
null_data

**#insights:**
1. Age , cabin and Embarked column have Null values.
2. Cabin column have 77 % Null value which can be Drop.
3. Age and Embarked column with Null value can be filled by appropriate values like mean, median and mode.

**2. Remove Outlier & Replace Null Values with appropriate values**

In [ ]:
titanic_train_data.boxplot(column = ['Age','SibSp','Parch','Fare'])

**finding appropriate value to fill NA of Age Column**

In [ ]:
average_age = np.round(titanic_train_data["Age"].mean())
average_age

In [ ]:
mode_age = np.round(titanic_train_data["Age"].mode())
mode_age

In [ ]:
median_age = np.round(titanic_train_data["Age"].median())
median_age

In [ ]:
sns.boxplot(titanic_train_data["Age"])

In [ ]:
sns.displot(titanic_train_data["Age"])

**Since Distribution is not symmetric so mean can not be used to fill NA cell, So filling NA of Age by median value**

In [ ]:
titanic_train_data["Age"].fillna(median_age, inplace = True) #filled the NA of Age with median value
titanic_train_data.isnull().sum() 

**Since Embarked is Categorical data type so filled NA of Embarked column by mode value**

In [ ]:
mode_Embarked = titanic_train_data["Embarked"].mode() # filled NA of Embarked column by mode value
mode_Embarked

**3. Drop down features that are incomplete and are not too relevant for analysis**

**drop Cabin column, because of 70 % NA value in it**

In [ ]:
titanic_train_data.drop("Cabin",axis = 1, inplace = True) 

In [ ]:
titanic_train_data["Embarked"].fillna(mode_Embarked[0], inplace = True) 

**PasswngerID and Ticket column may be drop because there is no affect on servival**

In [ ]:
titanic_train_data.drop(["PassengerId","Ticket"],axis=1, inplace = True)

In [ ]:
titanic_train_data.isnull().sum()

**4. Creating new Fields**

1. Create New Age Bands to improve  prediction Insights

2. Create a new feature called Family based on Parch and SibSp to get total count of family members on board

3. Create a Fare range feature if it helps our analysis

In [ ]:
titanic_train_data.head()

**## Age Band**

In [ ]:
titanic_train_data['Age_band']=0
titanic_train_data.loc[titanic_train_data['Age'] <=1, ['Age_band']] = "infant"
titanic_train_data.loc[(titanic_train_data['Age'] > 1) & (titanic_train_data['Age'] <= 12), ['Age_band']] = "Children"
titanic_train_data.loc[titanic_train_data['Age'] > 12, ['Age_band']] = "Adults"
titanic_train_data.head(3)

**## FARE BAND** (Pclass and Fare don't have any relation)

In [ ]:
titanic_train_data[titanic_train_data['Pclass']==3].head(5)

In [ ]:
plt.boxplot(titanic_train_data['Fare'])

In [ ]:
sns.displot(titanic_train_data['Fare'],kind ="hist")

In [ ]:
titanic_train_data['Fare'].max()

In [ ]:
titanic_train_data['Fare'].min()

In [ ]:
titanic_train_data['Fare_band']=0
titanic_train_data.loc[(titanic_train_data['Fare'] >= 0) & (titanic_train_data['Fare'] < 20), ['Fare_band']] = 1
titanic_train_data.loc[(titanic_train_data['Fare'] >= 20) & (titanic_train_data['Fare'] < 40), ['Fare_band']] = 2
titanic_train_data.loc[(titanic_train_data['Fare'] >= 40) & (titanic_train_data['Fare'] < 60), ['Fare_band']] = 3
titanic_train_data.loc[(titanic_train_data['Fare'] >= 60) & (titanic_train_data['Fare'] < 80), ['Fare_band']] = 4
titanic_train_data.loc[(titanic_train_data['Fare'] >= 80) & (titanic_train_data['Fare'] < 100), ['Fare_band']] = 5
titanic_train_data.loc[(titanic_train_data['Fare'] >= 100) & (titanic_train_data['Fare'] < 200), ['Fare_band']] = 6
titanic_train_data.loc[(titanic_train_data['Fare'] >= 200) , ['Fare_band']] = 7
titanic_train_data.head(3)

**Before dropping Name column, lets extract title from Name to mechanize relation between Name and Survivor.**

In [ ]:
titanic_train_data['Title']=titanic_train_data.Name.str.extract('([A-Za-z]+\.)', expand=False)
titanic_train_data.head(5)

In [ ]:
pd.crosstab(titanic_train_data["Title"],titanic_train_data["Sex"]) #giving count of Title respective of Sex

In [ ]:
titanic_train_data['Title'] = titanic_train_data['Title'].replace(['Lady', 'Countess','Capt', 'Col','Don', 'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona'], 'Rare')
titanic_train_data['Title'] = titanic_train_data['Title'].replace('Mlle', 'Miss')
titanic_train_data['Title'] = titanic_train_data['Title'].replace('Ms', 'Miss')
titanic_train_data['Title'] = titanic_train_data['Title'].replace('Mme', 'Mrs')

In [ ]:
title_mapping = {"Mr": 1, "Miss": 2, "Mrs": 3, "Master": 4, "Rare": 5}
titanic_train_data['Title'] = titanic_train_data['Title'].map(title_mapping)
titanic_train_data['Title'] = titanic_train_data['Title'].fillna(0)
titanic_train_data.head()

In [ ]:
titanic_train_data.drop('Name',axis=1,inplace=True)  ## Now drop Name Colume 

### Now we can convert features which contain strings to numerical values. This is required by most model algorithms. Doing so will also help us in achieving the feature completing goal.

- Converting Sex feature to a new feature called Gender where female=1 and male=0.

In [ ]:
titanic_train_data['Sex'] = titanic_train_data['Sex'].map( {'female': 1, 'male': 0} ).astype(int)
titanic_train_data.head()

In [ ]:
titanic_train_data['Embarked'] = titanic_train_data['Embarked'].map( {'S': 0, 'C': 1, 'Q': 2} ).astype(int)
titanic_train_data.head()

## 3.3 Post Profiling

In [ ]:
profile = ProfileReport(titanic_train_data,title = "Titanic report after data processing")
profile

In [ ]:
profile.to_file("Titanic Report after preprocessing.html")

## 4. Analysis through visualization

# 4.1 What is Total Count of Survivals and Victims?

In [ ]:
total_Survived = titanic_train_data[titanic_train_data['Survived']==1]['Survived'].count()
total_Victim = titanic_train_data[titanic_train_data['Survived']==0]['Survived'].count()
total_Survived,total_Victim

In [ ]:
titanic_train_data.groupby(['Survived'])['Survived'].count()

In [ ]:
titanic_train_data.Survived.value_counts()

In [ ]:
titanic_train_data.groupby(['Survived'])['Survived'].count().plot(kind='bar')

In [ ]:
plt = titanic_train_data.Survived.value_counts().plot(kind='bar')
plt.set_xlabel('died or survived')
plt.set_ylabel('Passenger Count')

**Insights:**
1. Only 342 Passengers survived outoff 891 Passengers.
2. and remaining 549 Passengers dead.


## 4.2 Which Gender has more Survival rate?

In [ ]:
titanic_train_data[titanic_train_data['Survived']==1][['Survived','Sex']].groupby(['Sex']).count()

In [ ]:
titanic_train_data.groupby(['Survived','Sex'])['Survived'].count()

In [ ]:
sns.countplot(data= titanic_train_data,x ='Survived',hue='Sex')

**Insight:**
Female had survived more than male.

# 4.3 What is Survival rate based on Person type(Male,female,Child)

In [ ]:
titanic_train_data.groupby(["Survived","Age_band"])["Survived"].count()

In [ ]:
titanic_train_data[titanic_train_data["Age_band"]=='Adults'].groupby(["Survived"])['Survived'].count().plot(kind='pie', figsize=(6, 6),explode=[0,0.05],autopct='%1.1f%%')
plt.set_title("Adults Survival Rate")

In [ ]:
titanic_train_data[titanic_train_data["Age_band"]=='infant'].groupby(["Survived"])['Survived'].count().plot(kind='pie', figsize=(6, 6),explode=[0,0.05],autopct='%1.1f%%')
plt.set_title("infant Survival Rate")

In [ ]:
titanic_train_data[titanic_train_data["Age_band"]=='Children'].groupby(["Survived"])['Survived'].count().plot(kind='pie', figsize=(6, 6),explode=[0,0.05],autopct='%1.1f%%')
plt.set_title("Children Survival Rate")

**Insights**
1. Survival Rate of Adults are lowest among other and Survival Rate of Infants are most among others.
2. Survival and Death Rate of Childrens are nearly Equal.


# 4.4 Did Economy Class had an impact on Survival?

In [ ]:
titanic_train_data.groupby(["Survived","Pclass"])['Survived'].count()

In [ ]:
sns.countplot(data = titanic_train_data,x='Survived',hue='Pclass')

**Insights:**
1. Yes, Economy Class impacted on the survival of Passengers.
2. Economy Class Passengers death count is lowest.

# 4.5 What is the Survival probaility based on Embarkment of Passengers?

In [ ]:
titanic_train_data.groupby(['Survived','Embarked'])['Survived'].count()

In [ ]:
sns.countplot(data = titanic_train_data,x='Embarked')

In [ ]:
sns.countplot(data = titanic_train_data,x='Survived',hue='Embarked')

In [ ]:
plt = titanic_train_data.groupby(['Embarked'])['Survived'].mean().plot(kind='bar')
plt.set_xlabel('Embarked')
plt.set_ylabel('Survival Probability')

**Insights:**
    1. Survival probability is maximum when passenger embarked at 1 i.e; C(Cherbourg) and minimum when passenger embarked at 0 i.e; S(Southampton).

# 4.6 How is Fare distributed for the Passengers?

In [ ]:
titanic_train_data[["Fare"]].plot(kind='hist')

In [ ]:
sns.displot(titanic_train_data['Fare'],bins=10)

**Insights:**
1. Most of fare lies between 0 to 100.
2. and maximum number of Passengers fare lies within 50.
3. Higher fare amount was paid by few passengers only

# 4.7 What was Average Fare by Pclass & Embark location?

In [ ]:
titanic_train_data.groupby(["Pclass"])["Fare"].mean()

In [ ]:
titanic_train_data.groupby(['Embarked'])["Fare"].mean()

**Insights:**
1. Average fare of Pclass 1 is highest
2.Average fare of passengers who embarked at C , S, Q was 27.25, 59.95 ,13.27 dollar respectively.


# 4.8 Segment Age in bins with size of 20.Also Correlate Age with Survival.

In [ ]:
sns.displot(data=titanic_train_data,x=titanic_train_data["Age"],kind='hist',bins=20)

In [ ]:
titanic_train_data["Age"].min()

In [ ]:
sns.displot(data = titanic_train_data[titanic_train_data['Survived']==1],x=titanic_train_data[titanic_train_data['Survived']==1]["Age"],kind='hist',bins=20)

**Insights:**
1. minimum age of Passenger was 0.42 year ie; nearly 6 months
2. maximum age of passenger was 80 which count was very few.
3. Averege age of passenger was 30.
4. Most of passengers were of age between 20 to 35.
5. Servival count is most for age between 20 to 35.

# 4.9 Did Solo Traveller has less chances of Survival?

In [ ]:
titanic_train_data['FamilySize']=0
titanic_train_data['FamilySize']=titanic_train_data['Parch']+titanic_train_data['SibSp']
titanic_train_data['SoloPassenger']=0
titanic_train_data.loc[titanic_train_data.FamilySize==0,'SoloPassenger']=1
#if passenger's familysize = 0 means passenger is solo then solopassenger = 1 else 0
titanic_train_data.head(3)

In [ ]:
titanic_train_data.groupby(["SoloPassenger","Survived"])["Survived"].count()

**Insights:**
1. Yes, Solo passengers had less chance to survive.

# 4.10 How did Total family size affected Survival Count?

4.11 How can you correlate Pclass/Age/fare with Survival rate?


4.12 Which features had most Impact on Survival rate?